#---------------------------------------
# MariaDB installation and configuration 
# tasks file
#---------------------------------------

- name: install maria-db and python 
  apt: 
    name: "{{ item }}"
    state: latest
  with_items:
    - mariadb-server 
    - python-pymysql
    - libmariadbclient-dev
    - python-dev
    - python-mysqldb
    - mysql-client
  become: yes

- name: Install the Python MySQLB module
  pip: name=MySQL-python

- name: configure maria-db
  template:
    src: 99-openstack.cnf.j2
    dest: /etc/mysql/mariadb.conf.d/99-openstack.cnf
  become: yes
  notify: restart mariadb

- name: Add .my.cnf
  template: src=my.cnf.j2 dest=~/.my.cnf mode=0600

- name: flush privileges
  command: 'mysql -ne "FLUSH PRIVILEGES"'
  changed_when: False
  become: yes 

- name: set root password
  mysql_user: 
    name: root 
    host: "{{ hostvars[ansible_host].inventory_hostname }}"
    password: "{{ db_root_password }}"
    state: present
  become: yes

- name: remove anonymous users
  mysql_user:
    name: ''
    host_all: yes
    state: absent
  become: yes

- name: Disallow root login remotely
  command: 'mysql -ne "{{ item }}"'
  with_items:
    -  DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: False
  become: yes

- name: remove test database
  mysql_db:
    name: test
    state: absent
  become: yes
  notify: flush privileges

- name: Remove test database and access to it
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
  changed_when: False
  ignore_errors: True
  become: yes
  notify: restart mariadb

  #----------------------------------------
  # KEYSTONE PREPARATION

- name: create db keystone
  mysql_db: 
    name: "{{ keystone.db_name }}"
    state: present
  become: yes

- name: set privileges on keystone DB
  mysql_user: 
    name: "{{ keystone.db_user }}"
    host: "{{ item }}"
    password: "{{ KEYSTONE_DBPASS }}" 
    priv: '*.*:ALL' 
    state: present
  with_items:
    - localhost
    - '%'
  changed_when: False
  become: yes
