- name: install rabbitmq-server
  apt: 
    name: rabbitmq-server 
    state: latest
  become: yes

- name: add rabbitmq user
  rabbitmq_user: 
    user: "{{ RABBIT_USER }}"
    password: "{{ RABBIT_PASS }}"
    configure_priv: .* 
    write_priv: .* 
    read_priv: .* 
    state: present
  become: yes