---
# handlers file for openstack_controller
- name: restart chrony
  service: name=chrony state=restarted
  become: yes

- name: restart mariadb
  service: name=mysql state=restarted
  become: yes

- name: restart memcached
  service: name=memcached state=restarted
  become: yes

- name: restart apache2
  service: name=apache2 state=restarted
  become: yes

- name: flush privileges
  command: 'mysql -ne "FLUSH PRIVILEGES"'
  changed_when: False
  become: yes 