# - hosts: all
#   roles: 
#     - host_prepare

# - hosts: all
#   roles: 
#     - openstack_network

- hosts: openstack_controller
  roles: 
    - openstack_controller
  environment: 
    OS_USERNAME: admin
    OS_PASSWORD: "{{ ADMIN_PASS }}"
    OS_PROJECT_NAME: admin
    OS_USER_DOMAIN_NAME: Default
    OS_PROJECT_DOMAIN_NAME: Default
    OS_AUTH_URL: http://{{ hostvars[ansible_host].inventory_hostname }}:35357/v3
    OS_IDENTITY_API_VERSION: 3

- hosts: openstack_compute
  roles:
    - openstack_nova