# somehow match users with the hosts

- hosts: cluster_nodes
  
  tasks:
  - name: update cache and install virt env
    apt: name={{ item }} state=latest update_cache=yes
    with_items:
      - qemu-kvm
      - libvirt-daemon-system
      - libvirt-clients
      - libvirt-dev
      - bridge-utils
    become: yes
  - name: enter libvirtd group
    user: 
      name: admin
      groups: libvirt
      append: yes
    become: yes

  - name: setup /etc/hosts file
    template: src=staging_hosts.k2 dest=/etc/hosts backup=yes
    tag: hosts